create table if not exists public.user_app_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  daily_goal smallint not null default 20 check (daily_goal in (10, 20, 30)),
  reminders_enabled boolean not null default false,
  streak_guard_enabled boolean not null default true,
  reminder_timezone text not null default 'Europe/Dublin',
  last_reminder_sent_on date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  created_at timestamptz not null default now()
);

alter table public.user_app_preferences enable row level security;
alter table public.push_subscriptions enable row level security;

drop policy if exists "users can read own app preferences" on public.user_app_preferences;
create policy "users can read own app preferences"
on public.user_app_preferences for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "users can insert own app preferences" on public.user_app_preferences;
create policy "users can insert own app preferences"
on public.user_app_preferences for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "users can update own app preferences" on public.user_app_preferences;
create policy "users can update own app preferences"
on public.user_app_preferences for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "users can read own push subscriptions" on public.push_subscriptions;
create policy "users can read own push subscriptions"
on public.push_subscriptions for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "users can insert own push subscriptions" on public.push_subscriptions;
create policy "users can insert own push subscriptions"
on public.push_subscriptions for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "users can delete own push subscriptions" on public.push_subscriptions;
create policy "users can delete own push subscriptions"
on public.push_subscriptions for delete
to authenticated
using (auth.uid() = user_id);

create index if not exists push_subscriptions_user_id_idx on public.push_subscriptions(user_id);
create index if not exists user_app_preferences_reminders_idx on public.user_app_preferences(reminders_enabled);

grant select, insert, update on public.user_app_preferences to authenticated;
grant select, insert, delete on public.push_subscriptions to authenticated;