-- Earnable streak protection.
-- A user can hold up to three unused shields and reserve one active shield at a time.
alter table public.user_app_preferences
  add column if not exists streak_shields smallint not null default 0,
  add column if not exists streak_protection_active boolean not null default false,
  add column if not exists streak_protection_activated_at timestamptz;

alter table public.user_app_preferences
  drop constraint if exists user_app_preferences_streak_shields_check;

alter table public.user_app_preferences
  add constraint user_app_preferences_streak_shields_check
  check (streak_shields between 0 and 3);

create table if not exists public.streak_protection_rewards (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  reward_date date not null,
  created_at timestamptz not null default now(),
  unique (user_id, reward_date)
);

create index if not exists streak_protection_rewards_user_date_idx
  on public.streak_protection_rewards(user_id, reward_date desc);

alter table public.streak_protection_rewards enable row level security;
revoke all on public.streak_protection_rewards from anon, authenticated;

create table if not exists public.streak_protected_days (
  user_id uuid not null references auth.users(id) on delete cascade,
  protected_date date not null,
  created_at timestamptz not null default now(),
  primary key (user_id, protected_date)
);

create index if not exists streak_protected_days_user_date_idx
  on public.streak_protected_days(user_id, protected_date desc);

alter table public.streak_protected_days enable row level security;

drop policy if exists "Users can read their own protected streak days" on public.streak_protected_days;
create policy "Users can read their own protected streak days"
on public.streak_protected_days
for select
to authenticated
using (auth.uid() = user_id);

revoke insert, update, delete on public.streak_protected_days from anon, authenticated;
grant select on public.streak_protected_days to authenticated;

create or replace function public.reward_streak_shield_for_activity(
  target_user uuid,
  reward_date date
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.user_app_preferences (user_id)
  values (target_user)
  on conflict (user_id) do nothing;

  insert into public.streak_protection_rewards (user_id, reward_date)
  values (target_user, reward_date)
  on conflict (user_id, reward_date) do nothing;

  if found then
    update public.user_app_preferences
    set streak_shields = least(3, streak_shields + 1),
        updated_at = now()
    where user_id = target_user
      and streak_shields < 3;
  end if;
end;
$$;

revoke all on function public.reward_streak_shield_for_activity(uuid, date) from public, anon, authenticated;

create or replace function public.award_streak_shield_from_practice()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  timezone_name text := 'Europe/Dublin';
  local_day date;
  qualifying_count integer;
begin
  if new.selected_answer is null or new.mode = 'mock' then
    return new;
  end if;

  begin
    select coalesce(nullif(reminder_timezone, ''), 'Europe/Dublin')
    into timezone_name
    from public.user_app_preferences
    where user_id = new.user_id;

    local_day := (new.created_at at time zone timezone_name)::date;

    select count(*)
    into qualifying_count
    from public.question_attempts attempt
    where attempt.user_id = new.user_id
      and attempt.selected_answer is not null
      and attempt.mode <> 'mock'
      and (attempt.created_at at time zone timezone_name)::date = local_day;
  exception when invalid_parameter_value then
    timezone_name := 'Europe/Dublin';
    local_day := (new.created_at at time zone timezone_name)::date;

    select count(*)
    into qualifying_count
    from public.question_attempts attempt
    where attempt.user_id = new.user_id
      and attempt.selected_answer is not null
      and attempt.mode <> 'mock'
      and (attempt.created_at at time zone timezone_name)::date = local_day;
  end;

  if qualifying_count >= 20 then
    perform public.reward_streak_shield_for_activity(new.user_id, local_day);
  end if;

  return new;
end;
$$;

drop trigger if exists question_attempts_award_streak_shield on public.question_attempts;
create trigger question_attempts_award_streak_shield
after insert on public.question_attempts
for each row
execute function public.award_streak_shield_from_practice();

create or replace function public.award_streak_shield_from_mock()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  timezone_name text := 'Europe/Dublin';
  local_day date;
begin
  begin
    select coalesce(nullif(reminder_timezone, ''), 'Europe/Dublin')
    into timezone_name
    from public.user_app_preferences
    where user_id = new.user_id;

    local_day := (new.created_at at time zone timezone_name)::date;
  exception when invalid_parameter_value then
    timezone_name := 'Europe/Dublin';
    local_day := (new.created_at at time zone timezone_name)::date;
  end;

  perform public.reward_streak_shield_for_activity(new.user_id, local_day);
  return new;
end;
$$;

drop trigger if exists mock_tests_award_streak_shield on public.mock_tests;
create trigger mock_tests_award_streak_shield
after insert on public.mock_tests
for each row
execute function public.award_streak_shield_from_mock();

revoke all on function public.award_streak_shield_from_practice() from public, anon, authenticated;
revoke all on function public.award_streak_shield_from_mock() from public, anon, authenticated;

create or replace function public.reconcile_streak_protection(target_user uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  preference record;
  timezone_name text := 'Europe/Dublin';
  today_local date;
  activation_date date;
  cursor_date date;
  day_active boolean;
  previous_day_active boolean;
begin
  select
    streak_protection_active,
    streak_protection_activated_at,
    reminder_timezone
  into preference
  from public.user_app_preferences
  where user_id = target_user
  for update;

  if not found or not preference.streak_protection_active then
    return;
  end if;

  timezone_name := coalesce(nullif(preference.reminder_timezone, ''), 'Europe/Dublin');

  begin
    today_local := (now() at time zone timezone_name)::date;
    activation_date := coalesce(
      (preference.streak_protection_activated_at at time zone timezone_name)::date,
      today_local
    );
  exception when invalid_parameter_value then
    timezone_name := 'Europe/Dublin';
    today_local := (now() at time zone timezone_name)::date;
    activation_date := coalesce(
      (preference.streak_protection_activated_at at time zone timezone_name)::date,
      today_local
    );
  end;

  if activation_date >= today_local then
    return;
  end if;

  cursor_date := activation_date;

  while cursor_date < today_local loop
    select exists (
      select 1
      from public.question_attempts attempt
      where attempt.user_id = target_user
        and attempt.selected_answer is not null
        and (attempt.created_at at time zone timezone_name)::date = cursor_date
    )
    into day_active;

    if not day_active then
      select
        exists (
          select 1
          from public.question_attempts attempt
          where attempt.user_id = target_user
            and attempt.selected_answer is not null
            and (attempt.created_at at time zone timezone_name)::date = cursor_date - 1
        )
        or exists (
          select 1
          from public.streak_protected_days protected_day
          where protected_day.user_id = target_user
            and protected_day.protected_date = cursor_date - 1
        )
      into previous_day_active;

      if previous_day_active then
        insert into public.streak_protected_days (user_id, protected_date)
        values (target_user, cursor_date)
        on conflict (user_id, protected_date) do nothing;

        update public.user_app_preferences
        set streak_protection_active = false,
            streak_protection_activated_at = null,
            updated_at = now()
        where user_id = target_user;

        exit;
      end if;
    end if;

    cursor_date := cursor_date + 1;
  end loop;
end;
$$;

revoke all on function public.reconcile_streak_protection(uuid) from public, anon, authenticated;
